FIXUP: CHROMIUM: ASoC: rt5677: allow multiple interrupt sources
When building for ARM targets:

sound/soc/codecs/rt5677.c: In function 'rt5677_irq_map':
sound/soc/codecs/rt5677.c:5185:2: error: implicit declaration of function 'set_irq_flags'

set_irq_flags() was removed with upstream commit eb811129ed9e ("ARM: Remove
ununsed set_irq_flags") after all its use had been converted to use the
standard API.

BUG=b:121045120, b:121046575
TEST=Build arm:allmodconfig

Change-Id: Ib427c35bde721a8b5ad6d482c0bb36edde10913a
Signed-off-by: Guenter Roeck <groeck@chromium.org>
Reviewed-on: https://chromium-review.googlesource.com/1520813
Reviewed-by: Fletcher Woodruff <fletcherw@chromium.org>
Reviewed-by: Ross Zwisler <zwisler@chromium.org>