CHROMIUM: tpm: cr50_i2c: Fixed wildcard formatting
The commit 88c117098547 ("CHROMIUM: tpm: cr50_i2c: handle small first
chunk") caused the kernel to no longer build with GCC. GCC is more
strict about the argument types for wildcard substitution and gives the
following error:

error: format '%zu' expects argument of type 'size_t', but argument 5
has type 'int' [-Werror=format=]
    burstcnt, buf_len, TPM_HEADER_SIZE);

BUG=chromium:927047
TEST=Copmile with both gcc and clang

Change-Id: I3017e5edbe6de24cc873795f719c0bc8cbb86703
Signed-off-by: Jon Flatley <jflat@chromium.org>
Reviewed-on: https://chromium-review.googlesource.com/1446791
Commit-Ready: ChromeOS CL Exonerator Bot <chromiumos-cl-exonerator@appspot.gserviceaccount.com>
Reviewed-by: Andrey Pronin <apronin@chromium.org>