UPSTREAM: drm/i915/dp: Fix compilation of intel_dp_hdcp_check_link
drivers/gpu/drm/i915/intel_dp.c: In function ‘intel_dp_hdcp_check_link’:
drivers/gpu/drm/i915/intel_dp.c:5191:26: error: ?: using integer constants in boolean context [-Werror=int-in-bool-context]
   return ret >= 0 ? -EIO : ret;

Fixes: 20f24d776d1b ("drm/i915: Implement HDCP for DisplayPort")
Signed-off-by: Chris Wilson <chris@chris-wilson.co.uk>
Cc: Daniel Vetter <daniel.vetter@ffwll.ch>
Cc: Ramalingam C <ramalingam.c@intel.com>
Cc: Sean Paul <seanpaul@chromium.org>
Cc: Jani Nikula <jani.nikula@linux.intel.com>
Signed-off-by: Sean Paul <seanpaul@chromium.org>
Link: https://patchwork.freedesktop.org/patch/msgid/20180118161025.22700-1-chris@chris-wilson.co.uk

BUG=b:141971239
TEST=boot Meep, run login_LoginSuccess, connect DP monitor

Signed-off-by: Chiou, Cooper <cooper.chiou@intel.com>
(cherry picked from commit b7fc1a9b7e62dcae40d51e83390cbb678ae5c6c2)

Change-Id: I97c8d9939d293571d232e5df422e725e663e0f08
Reviewed-on: https://chromium-review.googlesource.com/c/chromiumos/third_party/kernel/+/1878113
Reviewed-by: Sean Paul <seanpaul@chromium.org>
Reviewed-by: Stéphane Marchesin <marcheu@chromium.org>
Tested-by: Marco Chen <marcochen@chromium.org>
Tested-by: Cooper Chiou <cooper.chiou@intel.com>
Legacy-Commit-Queue: Commit Bot <commit-bot@chromium.org>
Commit-Queue: ChromeOS CL Exonerator Bot <chromiumos-cl-exonerator@appspot.gserviceaccount.com>
Commit-Queue: Cooper Chiou <cooper.chiou@intel.com>
Auto-Submit: Cooper Chiou <cooper.chiou@intel.com>