BACKPORT: FROMGIT: rtw88: add BT co-existence support
Both RTL8822BE/RTL8822CE are WiFi + BT combo chips. Since
WiFi and BT use 2.4GHz to transmit, it is important to
make sure they run concurrently without interfering each
other. To achieve this, WiFi driver requires a mechanism
to collaborate with BT, whether they share the antenna(s)
or not.

The final decision made by the co-existence mechanism is
to choose a proper strategy, or called "tdma/table", and
inform either firmware or hardware of the strategy.
To choose a strategy, co-existence mechanism needs to
have enough information from WiFi and BT.

BT information is provided through firmware C2H.
The contents describe the current status of BT, such as
if BT is connected or is idle, or the profile that is
being used.

WiFi information can be provided by WiFi itself. The WiFi
driver will call various of "notify" functions each time
the state of WiFi changed, such as WiFi is going to switch
channel or is connected. Also WiFi driver can know if it
shares antenna with BT by reading efuse content. Antenna
configuration of the module will finally get a different
strategy.

Upon receiving any information from WiFi or BT, the WiFi
driver will run the co-existence mechanism immediately.
It will set the RF antenna configuration according to the
strategy through the TDMA H2C to firmware and a hardware
table. Based on the tdma/table, WiFi + BT should work with
each other, and having a better user experience.

Fix backport errors due to incompatible pointer types

error: incompatible pointer types initializing
       'void (*)(struct ieee80211_hw *, struct ieee80211_vif *)'
       with an expression of type
       'void (struct ieee80211_hw *, struct ieee80211_vif *, u16)'
       (aka 'void (struct ieee80211_hw *, struct ieee80211_vif *,
        unsigned short)')
       [-Werror,-Wincompatible-pointer-types]

        .mgd_prepare_tx         = rtw_ops_mgd_prepare_tx,
                                  ^~~~~~~~~~~~~~~~~~~~~~

BUG=b:124400293
TEST=None

Signed-off-by: Yan-Hsuan Chuang <yhchuang@realtek.com>
Signed-off-by: Kalle Valo <kvalo@codeaurora.org>
(cherry picked from commit 4136214f7c46839c15f0f177fe1d5052302c0205
 git://git.kernel.org/pub/scm/linux/kernel/git/kvalo/wireless-drivers-next.git
 master)

Change-Id: I286197661bf437cdc516716aabf547ba77c0fb31
Reviewed-on: https://chromium-review.googlesource.com/1710378
Tested-by: Brian Norris <briannorris@chromium.org>
Commit-Ready: ChromeOS CL Exonerator Bot <chromiumos-cl-exonerator@appspot.gserviceaccount.com>
Legacy-Commit-Queue: Commit Bot <commit-bot@chromium.org>
Reviewed-by: Brian Norris <briannorris@chromium.org>