CHROMIUM: vhost: fix vhost ioctl signature to build with clang
Clang is particularly anal about signed vs unsigned comparisons and
doesn't like the fact that some ioctl numbers set the MSB, so we get
this error when trying to build vhost on aarch64:

v4.4/drivers/vhost/vhost.c:793:7: error: overflow converting case value to
switch condition type (3221794578 to 18446744072636378898) [-Werror,-Wswitch]
        case VHOST_GET_VRING_BASE:

Fix this by using unsigned ints in the function signature for
vhost_vring_ioctl().

BUG=chromium:797868
TEST=build kevin with USE="kvm_host" and CONFIG_VSOCK=m enabled

Change-Id: Id3e5bfe7aaa3a87926971aae230477ce73f7e5ed
Signed-off-by: Sonny Rao <sonnyrao@chromium.org>
Reviewed-on: https://chromium-review.googlesource.com/855522