FIXUP: CHROMIUM: add new syscall whitelist to alt-syscall
This new code breaks i386 builds.

security/chromiumos/alt-syscall.h:76:23: error: '__NR_accept' undeclared here
security/chromiumos/alt-syscall.h:76:23: error: '__NR_msgctl' undeclared here

and so on. Guess we don't support i386 anymore, so let's explicitly
restrict alt-syscall support to 64 bit builds.

Change-Id: I030d5da142eb8507dedf8e042dce341c119ca8e3
Signed-off-by: Guenter Roeck <groeck@chromium.org>
Reviewed-on: https://chromium-review.googlesource.com/1165885
Reviewed-by: Micah Morton <mortonm@chromium.org>