FIXUP: CHROMIUM: v4l: Add go2001 PCI codec driver.
The driver fails to build on many architectures, including arm and
arm64, with the following error.

drivers/media/pci/go2001/go2001_hw.c: In function 'go2001_map_buffer':
drivers/media/pci/go2001/go2001_hw.c:938:3: error:
	implicit declaration of function 'dma_cache_sync'

dma_cache_sync() is indeed only defined for a few architectures
in v4.14.y. Limit driver to X86 since that is the only architecture
where the driver is actually usable and where it has been tested.

BUG=chromium:430638
TEST=video tests

Change-Id: I13ec5558f5cb1edc804242b4b2136d1ce8b26122
Signed-off-by: Guenter Roeck <groeck@chromium.org>
Reviewed-on: https://chromium-review.googlesource.com/1666698
Legacy-Commit-Queue: Commit Bot <commit-bot@chromium.org>
Reviewed-by: Fletcher Woodruff <fletcherw@chromium.org>