UPSTREAM: powerpc: Mark the variable earlycon_acpi_spcr_enable maybe_unused
Re-use the object-like macro EARLYCON_USED_OR_UNUSED to mark
`earlycon_acpi_spcr_enable` as maybe_unused.

Fix the following warning (treated as error in W=1)

  CC      arch/powerpc/kernel/setup-common.o
In file included from ./include/linux/serial_8250.h:14:0,
                 from arch/powerpc/kernel/setup-common.c:33:
./include/linux/serial_core.h:382:19: error: ‘earlycon_acpi_spcr_enable’ defined but not used [-Werror=unused-const-variable=]
 static const bool earlycon_acpi_spcr_enable;
                   ^~~~~~~~~~~~~~~~~~~~~~~~~
cc1: all warnings being treated as errors

Signed-off-by: Mathieu Malaterre <malat@debian.org>
Signed-off-by: Greg Kroah-Hartman <gregkh@linuxfoundation.org>
(cherry picked from commit 219c7b06f3da9ac2b51ed671881b20f1b127daef)

BUG=b:74392237
TEST=Boot grunt with modified coreboot to add SPCR API table, and with
     just "earlycon" in the kernel command line.
     => kernel serial console contains message:
     [    0.000000] bootconsole [uart0] enabledq

Signed-off-by: Aashish Sharma <shraash@google.com>
Change-Id: I0158939d3708338161e45c11470e63fd7729d084
Reviewed-on: https://chromium-review.googlesource.com/c/chromiumos/third_party/kernel/+/3428844
Reviewed-by: Sean Paul <seanpaul@chromium.org>
Reviewed-by: Guenter Roeck <groeck@chromium.org>
Tested-by: Guenter Roeck <groeck@chromium.org>
Commit-Queue: Guenter Roeck <groeck@chromium.org>