FIXUP: UPSTREAM: drm: add missing ctx argument to plane transitional helpers
Missed one function call.

drivers/gpu/drm/arm/malidp_planes.c: In function 'malidp_de_plane_destroy':
drivers/gpu/drm/arm/malidp_planes.c:62:2: error:
	too few arguments to function 'drm_plane_helper_disable'

BUG=b:80589817
TEST=arm:allmodconfig

Change-Id: Ib4c4545bc5f2538b8e62d2a9a33c7e56f395d13e
Signed-off-by: Guenter Roeck <groeck@chromium.org>
Reviewed-on: https://chromium-review.googlesource.com/1162276
Reviewed-by: Sean Paul <seanpaul@chromium.org>