FIXUP: FROMLIST: jbd2: introduce jbd2_inode dirty range scoping
allmodconfig build fail.

ERROR: "jbd2_journal_inode_ranged_wait" [fs/ext4/ext4.ko] undefined!
ERROR: "jbd2_journal_inode_ranged_write" [fs/ext4/ext4.ko] undefined!

BUG=b:130521177, chromium:959968, b:133470926, b:65528573
TEST=allmodconfig

Change-Id: I3d6cbf2e4ebda885a1545683e1d81f9c3c75be31
Signed-off-by: Guenter Roeck <groeck@chromium.org>
Reviewed-on: https://chromium-review.googlesource.com/1673856
Legacy-Commit-Queue: Commit Bot <commit-bot@chromium.org>
Reviewed-by: Ross Zwisler <zwisler@google.com>