UPSTREAM: drm/amd/display: Fix potential NULL and mem leak in create_links
Found by smatch:
drivers/gpu/drm/amd/amdgpu/../display/dc/core/dc.c:148 create_links()
error: potential null dereference 'link->link_enc'.  (kzalloc returns
null)

BUG=b:72048470
TEST=boot Kahlee, run graphics_SanAngeles

Signed-off-by: Harry Wentland <harry.wentland@amd.com>
Reviewed-by: Tony Cheng <Tony.Cheng@amd.com>
Acked-by: Harry Wentland <harry.wentland@amd.com>
Signed-off-by: Alex Deucher <alexander.deucher@amd.com>
(cherry picked from commit edf38b58ecd847df75723fb90d4a1c3669b1e670)
Signed-off-by: Dominik Behr <dbehr@chromium.org>

Change-Id: Iac8f6b3d36f1d0637161513e8a5cb8fbd68140e2
Reviewed-on: https://chromium-review.googlesource.com/1012667
Commit-Ready: Dominik Behr <dbehr@google.com>
Tested-by: Dominik Behr <dbehr@google.com>
Reviewed-by: Stéphane Marchesin <marcheu@chromium.org>