FROMGIT: drm/amd/display: Remove extra pairs of parentheses in dce_calcs.c
The double parentheses are not needed. Removing them fixes multiple
warnings like this when building with clang:

drivers/gpu/drm/amd/amdgpu/../display/dc/calcs/dce_calcs.c:617:42:
  error: equality comparison with extraneous parentheses
    [-Werror,-Wparentheses-equality]
  if ((data->graphics_micro_tile_mode == bw_def_rotated_micro_tiling)) {

Signed-off-by: Matthias Kaehlcke <mka@chromium.org>
Reviewed-by: Guenter Roeck <groeck@chromium.org>
Reviewed-by: Harry Wentland <harry.wentland@amd.com>
Signed-off-by: Alex Deucher <alexander.deucher@amd.com>
(cherry picked from people.freedesktop.org ~agd5f/linux drm-next-4.17-wip
commit e60096eb2392172e879585f42e20910e04f4bcbf)

BUG=chromium:809829
TEST=USE="clang" emerge-kahlee chromeos-kernel-4_14
  => the warning in the commit message is not raised

Change-Id: If8e3c9aa5649ad38253eb95b13749f9c0181fead
Signed-off-by: Matthias Kaehlcke <mka@chromium.org>
Reviewed-on: https://chromium-review.googlesource.com/909713
Reviewed-by: Justin TerAvest <teravest@chromium.org>