UPSTREAM: soc: qcom: remove unused label
The newly added driver comes with a harmless warning:

drivers/soc/qcom/rmtfs_mem.c: In function 'qcom_rmtfs_mem_probe':
drivers/soc/qcom/rmtfs_mem.c:211:1: error: label 'remove_cdev' defined but not used [-Werror=unused-label]

This removes the unused label to avoid the warning.

Fixes: 702baebb8e00 ("soc: qcom: Remote filesystem memory driver")
Signed-off-by: Arnd Bergmann <arnd@arndb.de>
(cherry picked from commit d771d62e3139986cc62d2067b37ebbe33a6d3b08)

BUG=chromium:795946
BUG=b:79668211
TEST=Build and boot cheza.

Change-Id: I3b3624f5c984bf425553a2cf9876021b52e67e27
Signed-off-by: Ben Chan <benchan@chromium.org>
Reviewed-on: https://chromium-review.googlesource.com/1119403
Reviewed-by: Douglas Anderson <dianders@chromium.org>