Revert "FIXUP: FROMLIST: ASoC: SOF: Add Build support for SOF core and Intel drivers"
This reverts commit 357fc8baf30b2e804826651e14a85087ba9003f4.

Reason for revert: need to revert for sof v1.2 merge

Original change's description:
> FIXUP: FROMLIST: ASoC: SOF: Add Build support for SOF core and Intel drivers
>
> ACPI support is deeply intertwined into this code. Trying to build an image
> with ACPI disabled results in errors such as
>
> ERROR: "snd_soc_acpi_codec_list"
> 	[sound/soc/intel/common/snd-soc-acpi-intel-match.ko] undefined!
>
> Don't claim that it is not needed.
>
> BUG=b:130538528
> TEST=Build allmodconfig on non-ACPI system
>
> Change-Id: I9024e644a970d14d4904e2d1c4ff9f479337ab6e
> Signed-off-by: Guenter Roeck <groeck@chromium.org>
> Reviewed-on: https://chromium-review.googlesource.com/1662076
> Legacy-Commit-Queue: Commit Bot <commit-bot@chromium.org>
> Reviewed-by: Curtis Malainey <cujomalainey@chromium.org>

Bug: b:135490563
Signed-off-by: Curtis Malainey <cujomalainey@chromium.org>