CHROMIUM: Revert "fs: unexport vfs_read and vfs_write"
This reverts commit bd8df82be66698042d11e7919e244c8d72b042ca.

Commit bd8df82be666 ("fs: unexport vfs_read and vfs_write") states:

No modular users left.  Given that they take user pointers there is no
good reason to export it to drivers to start with.

Unfortunately, that isn't entirely true for Android, since both sdcardfs
and usb gadget extensions use it, resulting in the following build errors.

ERROR: "vfs_read" [fs/sdcardfs/sdcardfs.ko] undefined!
ERROR: "vfs_write" [fs/sdcardfs/sdcardfs.ko] undefined!
ERROR: "vfs_read" [drivers/usb/gadget/function/usb_f_mtp.ko] undefined!
ERROR: "vfs_write" [drivers/usb/gadget/function/usb_f_mtp.ko] undefined!

We also have to assume that the alt-syscall infrastructure will need it.

BUG=chromium:771410
TEST=Build allmodconfig

Change-Id: Ic0e0688ff58fe498707f27bf7aa443036f986dcf
Signed-off-by: Guenter Roeck <groeck@chromium.org>