UPSTREAM: ASoC: acpi: add missing includes for non-ACPI platforms
0-day reports compilation issues with non-ACPI platforms.

In file included from sound/soc/soc-acpi.c:17:0:
>> include/sound/soc-acpi.h:36:46: error: 'ACPI_ID_LEN' undeclared here
(not in a function); did you mean 'ACPI_FILE'?
    snd_soc_acpi_find_name_from_hid(const u8 hid[ACPI_ID_LEN])

 sound/soc/soc-acpi.c: At top level:
>> sound/soc/soc-acpi.c:174:16: error: expected declaration specifiers or
'...' before string constant
    MODULE_LICENSE("GPL v2");

Add missing include files.

Fixes: 7feb2f786a46 ("ASoC: move ACPI common code out of Intel/sst tree")
Signed-off-by: Pierre-Louis Bossart <pierre-louis.bossart@linux.intel.com>
Reviewed-by: Andy Shevchenko <andriy.shevchenko@linux.intel.com>
Acked-By: Vinod Koul <vinod.koul@intel.com>
Signed-off-by: Mark Brown <broonie@kernel.org>
(cherry picked from commit 845ab40092601630ec9eb58398a53b9a87b6900b)
Signed-off-by: samaga Prasanna Krishna <samaga.krishna@intel.corp-partner.google.com>

BUG=b:110025789
TEST=Test Audio use cases after full SOF series patches are applied.

Change-Id: I0a092252bfb1d89022bd37d6290ce6ba0a5bb177
Reviewed-on: https://chromium-review.googlesource.com/1120547
Commit-Ready: Curtis Malainey <cujomalainey@google.com>
Tested-by: Curtis Malainey <cujomalainey@google.com>
Reviewed-by: Curtis Malainey <cujomalainey@google.com>