UPSTREAM: Bluetooth: btusb: avoid unused function warning
The btusb_rtl_cmd_timeout() function is used inside of an
ifdef, leading to a warning when this part is hidden
from the compiler:

drivers/bluetooth/btusb.c:530:13: error: unused function 'btusb_rtl_cmd_timeout' [-Werror,-Wunused-function]

Use an IS_ENABLED() check instead so the compiler can see
the code and then discard it silently.

Fixes: d7ef0d1e3968 ("Bluetooth: btusb: Use cmd_timeout to reset Realtek device")
Signed-off-by: Arnd Bergmann <arnd@arndb.de>
Signed-off-by: Marcel Holtmann <marcel@holtmann.org>

(cherry picked from commit 42d22098127d6384f789107f59caae87d7520fc4)

BUG=b:139382142
TEST=none

Signed-off-by: Linux Patches Robot <linux-patches-robot@chromeos-missing-patches.google.com.iam.gserviceaccount.com>
Signed-off-by: Guenter Roeck <groeck@chromium.org>
Change-Id: I87e118ef5207f03e9957e0c9a93613d52955e9e5
Reviewed-on: https://chromium-review.googlesource.com/c/chromiumos/third_party/kernel/+/2142569
Reviewed-by: Sean Paul <seanpaul@chromium.org>
Reviewed-by: Miao-chen Chou <mcchou@chromium.org>