FIXUP: CHROMIUM: iwl7000: mvm: support new WoWLAN status FW API
With the offending patch patch, IWL7000 now depends on CONFIG_PM.
If CONFIG_PM is disabled, builds fail with:

ERROR: "iwl_mvm_send_wowlan_get_status"
	[drivers/net/wireless/iwl7000/iwlwifi/mvm/iwlmvm.ko] undefined!

The function is only available if CONFIG_PM is enabled.
Make the dependency explicit.

BUG=b:112923180
TEST=Build with CONFIG_PM disabled

Change-Id: Iae120c89f0824263bfe0941b655eabf9b8e2c9a4
Signed-off-by: Guenter Roeck <groeck@chromium.org>
Reviewed-on: https://chromium-review.googlesource.com/1196954
Reviewed-by: Kirtika Ruchandani <kirtika@chromium.org>