UPSTREAM: amdgpu/dc: Fix missing null checks in amdgpu_dm.c
From smatch:
error: we previously assumed X could be null

BUG=b:65489307
TEST=boot Kahlee, run graphics_SanAngeles

Acked-by: Christian Knig <christian.koenig@amd.com>
Reviewed-by: Harry Wentland <harry.wentland@amd.com>
Signed-off-by: Ernst Sjstrand <ernstp@gmail.com>
Signed-off-by: Alex Deucher <alexander.deucher@amd.com>
(cherry picked from commit 423788c7a866cb7f5265af9b96952e8a4bf48fd5)
Signed-off-by: Dominik Behr <dbehr@chromium.org>

Change-Id: If11d5a3c5c9b82fbe05daf025cd18443963410c8
Reviewed-on: https://chromium-review.googlesource.com/847257
Commit-Ready: Dominik Behr <dbehr@google.com>
Tested-by: Dominik Behr <dbehr@google.com>
Reviewed-by: Stéphane Marchesin <marcheu@chromium.org>