FIXUP: FROMLIST: ASoC: SOF: Add Sound Open Firmware driver core
If CONFIG_SND_SOC_SOF=y and CONFIG_SND_SOC_SOF_NOCODEC=m, builds fail with

   ld: sound/soc/sof/core.o: in function `sof_machine_check':
>> sound/soc/sof/core.c:269: undefined reference to `sof_nocodec_setup'
   ld: sound/soc/sof/sof-acpi-dev.o: in function `sof_acpi_probe':
>> sound/soc/sof/sof-acpi-dev.c:220: undefined reference to `sof_nocodec_setup'

This happens because sof_nocodec_setup() is called from code built into the
kernel but resides in a module.

Since sof_nocodec_setup() is called unconditionally from the SOF core
if CONFIG_SND_SOC_SOF_FORCE_NOCODEC_MODE=y, SND_SOC_SOF_NOCODEC must be
built into the kernel if SND_SOC_SOF=y. Add the necessary dependency.

sof_nocodec_setup() is called from sof-acpi-dev.c:sof_acpi_probe()
if CONFIG_SND_SOC_SOF_FORCE_NOCODEC_MODE=y. This results in the second
build failure if SND_SOC_SOF_NOCODEC=m and SND_SOC_SOF_ACPI=y. Since
we force SND_SOC_SOF_NOCODEC=y if SND_SOC_SOF=y, and SND_SOC_SOF is
selected by SND_SOC_SOF_ACPI, this problem is solved with the above
change as well.

This change does not affect existing Chrome OS configurations and thus
does not have functional impact on shipping images.

BUG=chromium:961916, b:130538528
TEST=Test Audio use cases for GLK

Change-Id: I4e87b999970b1f630dd8e5ddddcc9162ab9b50ea
Reported-by: kbuild test robot <lkp@intel.com>
Signed-off-by: Guenter Roeck <groeck@chromium.org>
Reviewed-on: https://chromium-review.googlesource.com/1662077
Legacy-Commit-Queue: Commit Bot <commit-bot@chromium.org>
Reviewed-by: Curtis Malainey <cujomalainey@chromium.org>