FIXUP: BACKPORT: platform/chrome: cros_ec_sensorhub: Add FIFO support
0-day reports:

drivers/platform/chrome/cros_ec_sensorhub_ring.c:130:4: error:
	cast between incompatible function types from 'cros_ec_sensorhub_push_samples_cb_t'

Casting of function pointers is undefined in C. Let's avoid it and
typecast callback function arguments instead.

Also get rid of cros_ec_sensorhub_[un]register_push_sample and
call cros_ec_sensorhub_[un]register_push_data directly.

Drop define of CROS_EC_SENSOR_BROADCAST as it isn't used anywhere and
since it depended on CROS_EC_SENSOR_PDEV_MAX which is not defined.

BUG=chromium:946178
TEST=Build with W=1 and CONFIG_IIO_CROS_EC_SENSORS_RING={n,m}

Change-Id: Ie5743ac08dc743c8cbd8435559fadd61df3a5797
Signed-off-by: Guenter Roeck <groeck@chromium.org>
Reviewed-on: https://chromium-review.googlesource.com/c/chromiumos/third_party/kernel/+/2270512
(cherry picked from commit 0465b7dbe1f40c07da616eb08756e5437d6be4f7)
Reviewed-on: https://chromium-review.googlesource.com/c/chromiumos/third_party/kernel/+/2450929
Tested-by: Gwendal Grignou <gwendal@chromium.org>
Commit-Queue: Gwendal Grignou <gwendal@chromium.org>