FIXUP: CHROMIUM: FROMLIST: soc: qcom: Add GENI based QUP Wrapper driver
Building QCOM_GENI_SE as module results in:

drivers/soc/qcom/qcom-geni-se.c:65:14: error:
	redefinition of geni_read_reg_nolog

and similar errors since both shim and real functions are declared.
Avoid the problem by using IS_ENABLED() instead of ifdef.

Note: This is just a workaround. Per upstream comments, there should
be no shim functions in the first place.

BUG=chromium:795946
TEST=Build and boot

Change-Id: Ie78cb253621a6cf972c1342ca1f5b943f3b9e4a2
Signed-off-by: Guenter Roeck <groeck@chromium.org>
Reviewed-on: https://chromium-review.googlesource.com/933093
Reviewed-by: Douglas Anderson <dianders@chromium.org>