CHROMIUM: ASoC: SOF: add mm.h
0-day complains that on some architectures such as m68k mm_struct is not
defined. Make sure it's added.

In file included from ./arch/m68k/include/asm/pgtable_mm.h:148,
                 from ./arch/m68k/include/asm/pgtable.h:5,
                 from sound/soc/sof/pm.c:15:
./arch/m68k/include/asm/motorola_pgtable.h: In function 'pgd_offset':
./arch/m68k/include/asm/motorola_pgtable.h:199:11: error: dereferencing pointer to incomplete type 'const struct mm_struct'
  return mm->pgd + pgd_index(address);
           ^~
In file included from ./arch/m68k/include/asm/pgtable_mm.h:148,
                 from ./arch/m68k/include/asm/pgtable.h:5,
                 from sound/soc/sof/core.c:15:
./arch/m68k/include/asm/motorola_pgtable.h: In function 'pgd_offset':
./arch/m68k/include/asm/motorola_pgtable.h:199:11: error: dereferencing pointer to incomplete type 'const struct mm_struct'
  return mm->pgd + pgd_index(address);

Signed-off-by: Pierre-Louis Bossart <pierre-louis.bossart@linux.intel.com>
(cherry picked from commit 0fee76c9ff8cfcdb89bf5967cf14b7dd44a0e15f)
(cherry picked from commit f1b3bcfbb169930ccef74db7aaee2c3f35b0ca44)
Signed-off-by: Samaga Prasanna Krishna <samaga.krishna@intel.corp-partner.google.com>
Link:https://github.com/thesofproject/linux/commit/f1b3bcfbb169930ccef74db7aaee2c3f35b0ca44

BUG=b:110025789
TEST=Test Audio use cases after full SOF series patches are applied.

Change-Id: If7fda42d25b68b07e4836945b49131d2476dd458
Reviewed-on: https://chromium-review.googlesource.com/1308068
Commit-Ready: ChromeOS CL Exonerator Bot <chromiumos-cl-exonerator@appspot.gserviceaccount.com>
Tested-by: Curtis Malainey <cujomalainey@chromium.org>
Reviewed-by: Curtis Malainey <cujomalainey@chromium.org>