FIXUP: BACKPORT: audit: convert sessionid unset to a macro
The commit log of commit 3e979f27ac4 ("BACKPORT: audit: convert sessionid
unset to a macro") states "In 4.14, the initialization is done in
init_task.h instead of init_task.c."

However, the backport does not take into account that the newly used
AUDIT_SID_UNSET requires an additional include file. It does include
the required file in init_task.c, but it isn't needed there because
the initialization is now elsewhere.

This results in the following build error, as reported by 0day.

In file included from arch/ia64/kernel/init_task.c:15:
>> include/linux/init_task.h:124:15: error: 'AUDIT_SID_UNSET' undeclared here
     .sessionid = AUDIT_SID_UNSET,

BUG=chromium:918980
TEST=Build affected configurations.

Change-Id: I53d56ea9aa28ff9eb5db1b5e589a1803e988f049
Signed-off-by: Guenter Roeck <groeck@chromium.org>
Reviewed-on: https://chromium-review.googlesource.com/1418073
Commit-Ready: Dmitry Torokhov <dtor@chromium.org>
Tested-by: Dmitry Torokhov <dtor@chromium.org>
Reviewed-by: Dmitry Torokhov <dtor@chromium.org>
Reviewed-by: Robert Kolchmeyer <rkolchmeyer@google.com>