UPSTREAM: drm/amd/pp: Fix static checker warning
error: uninitialized symbol 'xxxx'

BUG=b:112542653
TEST=boot Grunt, run graphics_SanAngeles and login_LoginSuccess

Reviewed-by: Alex Deucher <alexander.deucher@amd.com>
Signed-off-by: Rex Zhu <Rex.Zhu@amd.com>
Signed-off-by: Alex Deucher <alexander.deucher@amd.com>
(cherry picked from commit 63e138abf0761c7ea3dcb29060bfd48a34e58ecf)
Signed-off-by: Dominik Behr <dbehr@chromium.org>

Change-Id: Idf0f8d2d0be8fac210a68ea65f21a18bd7e1cc68