FIXUP: CHROMIUM: FROMLIST: soc: qcom: Add GENI based QUP Wrapper driver
Since commit d141fda9a7c6 ("FIXUP: CHROMIUM: FROMLIST: tty: serial:
msm_geni_serial: Add serial driver support for GENI based QUP"),
the QCOM serial driver is always built into the kernel. Since it depends
on QCOM_GENI_SE, it does not make sense to have QCOM_GENI_SE buildable
as module. Make it bool as well to avoid undefined references such as

qcom_geni_serial.c:(.text+0x1d0): undefined reference to `geni_read_reg_nolog'
qcom_geni_serial.c:(.text+0x804): undefined reference to `geni_se_resources_on'
qcom_geni_serial.c:(.text+0x820): undefined reference to `geni_se_resources_off'
qcom_geni_serial.c:(.text+0x91c): undefined reference to `geni_write_reg_nolog'

BUG=chromium:795946
TEST=Build arm64:allmodconfig

Change-Id: I2aa9c63676e6328e52167a6c7b6669c49ba177f0
Signed-off-by: Guenter Roeck <groeck@chromium.org>
Reviewed-on: https://chromium-review.googlesource.com/938156
Reviewed-by: Douglas Anderson <dianders@chromium.org>