FROMGIT: drm/amd/powerplay: Remove extra pair of parentheses
The double parentheses are not needed. Removing them fixes the following
warning when building with clang:

drivers/gpu/drm/amd/powerplay/smumgr/tonga_smumgr.c:419:29:
  error: equality comparison with extraneous parentheses
    [-Werror,-Wparentheses-equality]
  if ((data->vdd_gfx_control == SMU7_VOLTAGE_CONTROL_BY_SVID2)) {

Reviewed-by: Guenter Roeck <groeck@chromium.org>
Signed-off-by: Matthias Kaehlcke <mka@chromium.org>
Signed-off-by: Alex Deucher <alexander.deucher@amd.com>
(cherry picked from people.freedesktop.org ~agd5f/linux drm-next-4.17-wip
commit d5b8956f4199a1e6ce006f0402bfe4c9d578bc44)

BUG=chromium:809829
TEST=build for kahlee

Change-Id: I1ce108d6d664d75ebf3232e00809c32179b4d034
Signed-off-by: Matthias Kaehlcke <mka@chromium.org>
Reviewed-on: https://chromium-review.googlesource.com/907639
Reviewed-by: Guenter Roeck <groeck@chromium.org>
Reviewed-by: Justin TerAvest <teravest@chromium.org>