FROMGIT: drm/msm: fix msm_rd_dump_submit prototype
The prototype of msm_rd_dump_submit() has recently changed. However,
we have two declarations of this functions, and the other one
remains the old version, leading to this:

drivers/gpu/drm/msm/msm_gpu.c: In function 'recover_worker':
drivers/gpu/drm/msm/msm_gpu.c:295:23: error: passing argument 1 of 'msm_rd_dump_submit' from incompatible pointer type [-Werror=incompatible-pointer-types]

This changes the second one to match the first again.

Fixes: 2165e2b9cba2 ("drm/msm: split rd debugfs file")
Signed-off-by: Arnd Bergmann <arnd@arndb.de>
Signed-off-by: Rob Clark <robdclark@gmail.com>

BUG=chromium:795946
TEST=Build and boot

Change-Id: Ib5e334684a454b1de11938709a19c73bceec07f5
Signed-off-by: Douglas Anderson <dianders@chromium.org>
(cherry picked from commit e6756d7c1a7ebe04def1b24b45ce01ef6c4175bc
 git://people.freedesktop.org/~robclark/linux robclark/msm-next)
Reviewed-on: https://chromium-review.googlesource.com/864784