ASoC: SoF: fix broken Kconfig dependency
Currently the SoF code is missing a Kconfig dependency that allows you to
define a kernel config which will fail to build with the following:

ERROR: "snd_hdac_ext_bus_link_power_down"
[sound/soc/sof/intel/snd-sof-intel-hda-common.ko] undefined!

ERROR: "snd_hdac_ext_bus_ppcap_int_enable"
[sound/soc/sof/intel/snd-sof-intel-hda-common.ko] undefined!

ERROR: "hda_dsp_ctrl_init_chip"
[sound/soc/sof/intel/snd-sof-intel-hda-common.ko] undefined!

ERROR: "snd_hdac_ext_bus_ppcap_enable"
[sound/soc/sof/intel/snd-sof-intel-hda-common.ko] undefined!

ERROR: "snd_hdac_ext_bus_link_power_down_all"
[sound/soc/sof/intel/snd-sof-intel-hda-common.ko] undefined!

A kernel config that shows this issue can be found here:

https://crrev.com/c/1372574

Fix this by selecting SND_SOC_SOF_HDA in the presence of
SND_SOC_SOF_HDA_COMMON.  This will also pull in SND_HDA_EXT_CORE, allowing
all dependencies to be resolved.

I've checked the tip-of-tree external SoF code (branch topic/sof-dev) and
it does not have this issue.

BUG=none
TEST=Build v4.14 kernel with config specified in above crrev link.

Change-Id: I1fe21d557aa83ecb2e0965f65c3d45144f5b41d4
Signed-off-by: Ross Zwisler <zwisler@google.com>
Reviewed-on: https://chromium-review.googlesource.com/1372576
Commit-Ready: Ross Zwisler <zwisler@chromium.org>
Tested-by: Ross Zwisler <zwisler@chromium.org>
Reviewed-by: Curtis Malainey <cujomalainey@chromium.org>