FIXUP: CHROMIUM: iwl7000: refactor the SAR tables from mvm to acpi
Builds with ACPI disabled fail.

drivers/net/wireless/iwl7000/iwlwifi/xvt/xvt.c:858:29: error:
	passing argument 1 of 'iwl_sar_select_profile' from incompatible pointer type
drivers/net/wireless/iwl7000/iwlwifi/xvt/../fw/acpi.h:208:19: note:
	expected 'struct iwl_fw_runtime *' but argument is of type 'struct iwl_fw_runtime *'

and similar errors.

BUG=b:141494459
TEST=Build iwl7000 with ACPI disabled

Change-Id: Ia4bde8daca7ce95e258b024252e7c64d7f7ceb74
Signed-off-by: Guenter Roeck <groeck@chromium.org>
Reviewed-on: https://chromium-review.googlesource.com/c/chromiumos/third_party/kernel/+/1860688
(cherry picked from commit f6a16373b6230786a993480ca030e549d9b4d49b)
Reviewed-on: https://chromium-review.googlesource.com/c/chromiumos/third_party/kernel/+/1918084
Reviewed-by: Kirtika Ruchandani <kirtika@chromium.org>
Commit-Queue: Kirtika Ruchandani <kirtika@chromium.org>