FIXUP: CHROMIUM: intel_telemetry: Export API to provide debug info
0day reports:
drivers/platform//x86/intel_telemetry_debugfs.c:544:5: error:
	redefinition of 'telem_soc_states_display'
arch/x86/include/asm/intel_telemetry.h:149:19: note:
	previous definition of 'telem_soc_states_display' was here

This happens if INTEL_TELEMETRY is built as module, which is not recognized
by the include file.

BUG=b:78841592
TEST=Build x86_64:allmodconfig

Change-Id: If1e556a3813a00b438c34dd8f21535b9e05f29d8
Signed-off-by: Guenter Roeck <groeck@chromium.org>
Reviewed-on: https://chromium-review.googlesource.com/1153217
Reviewed-by: Furquan Shaikh <furquan@chromium.org>