FROMGIT: drm/amd/powerplay: Fix enum mismatch
In several locations the driver uses AMD_CG_STATE_UNGATE (type enum
amd_clockgating_state) instead of AMD_PG_STATE_UNGATE (type enum
amd_powergating_stat) and vice versa. Both constants have the same
value, so this doesn't cause any problems, but we still want to pass
the correct type.

Fixing the mismatch resolves multiple warnings like this when building
with clang:

drivers/gpu/drm/amd/amdgpu/../powerplay/hwmgr/cz_clockpowergating.c:169:7:
  error: implicit conversion from enumeration type 'enum
  amd_powergating_state' to different enumeration type 'enum
  amd_clockgating_state' [-Werror,-Wenum-conversion]
    AMD_PG_STATE_UNGATE);

Reviewed-by: Guenter Roeck <groeck@chromium.org>
Signed-off-by: Matthias Kaehlcke <mka@chromium.org>
Signed-off-by: Alex Deucher <alexander.deucher@amd.com>
(cherry picked from people.freedesktop.org ~agd5f/linux drm-next-4.17-wip
commit 8717b5f6d321d2f5b481bfbed9b498e96f681a23)

BUG=chromium:809829
TEST=build for kahlee

Change-Id: I93c5a66e10f2b7fe941e7138b3c8b8d5856cd9df
Signed-off-by: Matthias Kaehlcke <mka@chromium.org>
Reviewed-on: https://chromium-review.googlesource.com/907638
Reviewed-by: Guenter Roeck <groeck@chromium.org>
Reviewed-by: Justin TerAvest <teravest@chromium.org>