FIXUP: UPSTREAM: drm/msm/gpu: avoid deprecated do_gettimeofday
After v4.18, tv_sec in struct timespec64 is an unsigned long long.
In v4.14, where y2038 conversion was not yet complete, struct timespec64
is mapped to struct timespec, where tv_sec is defined as unsigned long
on 64-bit systems and as unsigned long long otherwise. This results in
the following build errors/warnings, reported by 0-day.

drivers/gpu/drm/msm/msm_gpu.c:282:27: error:
	format '%lld' expects argument of type 'long long int',
	but argument 3 has type '__kernel_time_t {aka long int}'
drivers/gpu/drm/msm/msm_gpu.c:282:27: warning:
	format '%lld' expects argument of type 'long long int',
	but argument 3 has type '__kernel_time_t {aka long int}'

Fix the problem by typecasting tv_sec to unsigned long long; this should
address all different definitions.

BUG=b:80589817
TEST=arm64:allmodconfig

Change-Id: I28a72c078d89dd2c29987e5e3eb0c66caf5bd190
Signed-off-by: Guenter Roeck <groeck@chromium.org>
Reviewed-on: https://chromium-review.googlesource.com/c/chromiumos/third_party/kernel/+/2196212
Reviewed-by: Douglas Anderson <dianders@chromium.org>